### ISSUE TITLE
Very inconvenient display hud parts

### ISSUE THREAD

**Issue by h9lk** [n0kk/ahud#97] opened 2017-10-29 11:26 UTC
Can u fix this plz?

![1](https://user-images.githubusercontent.com/32390006/32143079-211699ba-bcb5-11e7-87a8-7d2ff0522c70.jpg)
![2](https://user-images.githubusercontent.com/32390006/32143080-2134c9c6-bcb5-11e7-8c61-f4247dc790e0.jpg)
![3](https://user-images.githubusercontent.com/32390006/32193549-b0b0b196-bdc8-11e7-8333-85359a59211f.jpg)

**Comment by n0kk** [comment] 2017-10-31 19:34
Magic spells HUD elements overlapping are now fixed in the latest update. The contracts bug in the 2nd pic I'm unable to reproduce. I've also never touched the files that control those HUD elements so I'm not of the cause.

**Comment by h9lk** [comment] 2017-10-31 19:36
Ok, thx for fix N0kk, god bless u

**Closed** 2017-10-31 21:27 UTC
Labels: fixed

**Comment by h9lk** [comment] 2017-11-04 23:10
After fix
![4](https://user-images.githubusercontent.com/32390006/32410318-79ac3b3e-c1ce-11e7-8844-20f7e158f5e7.jpg)

**Comment by n0kk** [comment] 2017-11-05 03:48
I forgot the medic charge meter is wider than the low ammo box... I'll fix this in the next update but if you want to resolve this now, `hudlayout.res` in the scripts folder, increase the xpos of *HudSpellMenu* . 

Thank you for checking this out though; I mostly don't look over it too much because the Halloween event is a brief period in the year

**Comment by h9lk** [comment] 2017-11-06 10:08
No problem
![5](https://user-images.githubusercontent.com/32390006/32435712-c7540036-c2f2-11e7-9f57-703a98318cec.jpg)
And bug who i can't screenshot, if u start search map -> with load show 'maps vote' 0% -> after this all 3 maps change on 'error' and vote too

**Comment by n0kk** [comment] 2017-11-07 23:50
The invite notification must be a game bug since I haven't had it at all while playing, nor have I touched the file that controls it. 

The map vote is for sure a game bug as I've had it on the default HUD and seen streamers encounter it with other custom HUDs.

**Comment by h9lk** [comment] 2017-11-09 08:17
Sry, if i waste ur time

**Comment by n0kk** [comment] 2017-11-15 03:56
Fixed (removed) in the newest update.
